version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  testdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - testdata:/var/lib/postgresql/data

volumes:
  testdata:
    external: true
  data:
    external: true